# Generated by Django 2.1.2 on 2018-10-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('title', models.CharField(help_text='Название работ', max_length=50)),
                ('price', models.IntegerField(help_text='Цена услуги')),
                ('countru', models.CharField(help_text='Страна', max_length=15)),
                ('citi', models.CharField(help_text='Город', max_length=15)),
                ('subway_ststion', models.CharField(help_text='Город', max_length=15)),
                ('description', models.TextField(help_text='Описание')),
            ],
        ),
    ]
